### ISSUE TITLE
webpack: Failed to compile

### ISSUE THREAD

**Issue by Jarajesh** [ebavs/webpack-es6-tutorial#1]
I cloned the repository and did a npm install. 
Ran npm run serve

`ERROR in ./src/style.scss
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '~bootstrap/dist/css/bootstrap.css';
|
| main {
 @ ./src/index.js 4:0-22
 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/index.js`

**Comment by fromcouch** [comment]
what version of node do you have? I just did:

    npm install
    npm run serve

in isolated folder and works fine.

Please, do you could install loaders separately?

    npm install --save-dev style-loader@latest css-loader@latest sass-loader@latest

**Comment by Jarajesh** [comment]
I am using node 8.12.0 and npm 6.4.1
tried your resolution its still throwing the same error.

**Comment by fromcouch** [comment]
error means that you haven't installed loaders. Do you could verify that you have loaders installed?
